### PR TITLE
feat: Add Client Scopes of Client

### PR DESCRIPTION
**Pull request by M4d40**
This is not the same Client Scopes that already exists.
Currently only Client Scopes -> Default Client Scopes are added.
This PR will Add the support to also get/add/delete
Clients -> YourClient -> Client Scopes -> Default/Optional Client Scopes

### CODE REVIEW

**Comment by ryshoooo** [comment]
Hi @M4d40 

Thanks a lot for your contribution :) Make sure to follow our [Contribution guidelines](https://github.com/marcospereirampj/python-keycloak/blob/master/CONTRIBUTING.md) in order to get this PR through the pipeline :)

**Comment by M4d40** [comment]
@ryshoooo i fixed the commit and linting errors and added all tests for the new code, but i'm not sure, how to fix the error in "check-docs" since i didn't touch the file listed in the error or anything related to it. Can you help me with this one?

**Comment by M4d40** [comment]
Last error is now fixed, it was in the Docstrings (missing doubled double-point in the: "`Payload example::`" )

All tests/checks finally passed now.

**Comment by ryshoooo** [comment]
Thanks a lot @M4d40 :) LGTM!

**Pull request merged**
