### PR TITLE
fix: deprecation warnings in keycloak_admin.py

### LINKED ISSUE #422: Deprecation warnings with 2.13.2 in admin module
After updating to 2.13.2, I keep getting these warnings:
```
/keycloak/keycloak_admin.py:1445: DeprecatedWarning: realm_name is deprecated as of 2.13.0 and will be removed in 3.0.0. Use the connection.realm_name property instead
    params_path = {"realm-name": self.realm_name, "id": client_id}
```
```
/keycloak/keycloak_admin.py:152: DeprecatedWarning: auto_refresh_token is deprecated as of 2.13.0 and will be removed in 3.0.0. Auto-refresh will be implicitly set for all requests
    self.auto_refresh_token = auto_refresh_token
```

### PR DESCRIPTION
**Pull request by pehala**
Fixes #422

### CODE REVIEW

**Comment by ryshoooo** [comment]
Hi @pehala 

LGTM, except for the removal of `auto_refresh_token` attribute. I understand that it's not "needed", however removing it in this PR would introduce a breaking change. So there are 2 options:

1. Keep `auto_refresh_token` attribute in the KeycloakAdmin class, i.e. revert the deletion
2. Update the commit message to include a breaking change note as conventional commits specify

I'm more prone towards the option 1. The `python-keycloak` version 3.0.0 should have all of these deprecated attributes completely removed, not just one.

**Comment by pehala** [comment]
I can revert the deletion. However, that would not solve the false deprecation warnings when using KeycloakAdmin. Is there a way to keep the attribute and have no deprecation warnings?

**Comment by ryshoooo** [comment]
> I can revert the deletion. However, that would not solve the false deprecation warnings when using KeycloakAdmin. Is there a way to keep the attribute and have no deprecation warnings?

A solution could be something like

```
if auto_refresh_token is not None:
    self.auto_refresh_token = auto_refresh_token
```

**Comment by pehala** [comment]
@ryshoooo Thanks, fixed

**Review by ryshoooo — APPROVED** [review]

**Pull request merged**
