### PR TITLE
Auto refresh admin token

### LINKED ISSUE #28: KeycloakAdmin expired access_token
When _KeycloakAdmin_'s _access_token_ expires, call to the api will return _KeylcoakAuthenticationError_.

There is no easy way to refresh the token. Although you have _refresh_token_, the _KeycloakOpenID_ instance used to get the _access_token_ is not persisted. And thus it's _refresh_token_ method is not available.

It would be nice to have a kind of "auto_refresh" feature that would retry the request with a refreshed token whenever the _access_token_ expires.

### PR DESCRIPTION
**Pull request by gt-novelt**
Saves the necessary information to retrieve admin token in the KeycloakAdmin instance.
Adds a new _auto_refresh_token_ parameter on instantiation. This parameter is a list of methods you want KeycloakAdmin to retry request with refreshed token on stale token.
When the admin token is stale, it will try to use _refresh_token_ to get a new token and if that fails, it will ask for a complete new one.

This allows to optionally have a single instance of KeycloakAdmin throughout the whole application.

Fixes #28 and #21

### CODE REVIEW

**Comment by nikolyabb** [comment]
@marcospereirampj can you let me know if you are planning to add this code to the upstream, please?

**Comment by gt-novelt** [comment]
Note that latest commit 1e806554b554b69bab03a1a8e82778994cccb2f3 adds retry on **POST** to overcome Keycloak closing connection after 1min of inactivity.

**Review by marcospereirampj — APPROVED** [review]

**Comment by marcospereirampj** [comment]
@gt-novelt @nikolyabb Sorry for my big delay. I'll release the version today.

**Comment by gt-novelt** [comment]
no worries @marcospereirampj. Very handy lib by the way 😃

**Comment by lucasln** [comment]
Thank you @marcospereirampj ,when are you planning to generate a new pypi package for python-keycloak ?  https://pypi.org/project/python-keycloak/#history

**Comment by ethompsy** [comment]
Not only should this be the default behavior, but it _should_ be documented somewhere. It took forever to figure out why queries start blowing up after working for a while. I don't even know how I found this PR and only after looking at the code did I find that adding `auto_refresh_token=['get', 'put', 'post', 'delete']` to my KeycloakAdmin object fixed hundreds of 401s.

**Pull request merged**
