### PR TITLE
Fix speling

### PR DESCRIPTION
**Pull request by ecederstrand**

### CODE REVIEW

**Comment by ryshoooo** [comment]
Hi Erik :) Feel free to submit PR here https://github.com/adamatics/adamatics-keycloak. My only comment is that the examples in the README file should be updated as well to the correct spelin.

**Comment by ryshoooo** [comment]
Hi Erik :) Feel free to submit PR here https://github.com/adamatics/adamatics-keycloak. My only comment is that the examples in the README file should be updated as well to the correct spelin.

**Comment by ryshoooo** [comment]
Hi Erik :) Feel free to submit PR here https://github.com/adamatics/adamatics-keycloak. My only comment is that the examples in the README file should be updated as well to the correct spelin.

**Comment by ecederstrand** [comment]
Fixed spelling everywhere now.

**Review by ryshoooo — COMMENTED** [review]
LGTM. If I can ask you to rebase your commits to follow conventional commits and update your branch with the latest master. I'll approve and merge then :)

**Review by ryshoooo — APPROVED** [review]
LGTM :) Thanks for the contribution!

**Pull request merged**
