### PR TITLE
bug fix on the get groups url

### PR DESCRIPTION
**Pull request by harmannkibue**
Have added the bug fix on getting groups url

### CODE REVIEW

**Comment by Eric-Fontana-Indico** [comment]
please approve this!

**Comment by AMontagu** [comment]
https://github.com/marcospereirampj/python-keycloak/pull/267

**Comment by thomasmuders-imtf** [comment]
Please approve this, it is breaking my code.

**Comment by ryshoooo** [comment]
Hi. Due to the lack of activity from the maintainers, we've decided to fork this repository (https://github.com/adamatics/adamatics-keycloak) and take the maintenance burden, in order to keep the python keycloak client fresh and updated. We aim to release very frequently, but we also aim to increase the test coverage dramatically. We've included your changes in our forked release, see https://pypi.org/project/adamatics-keycloak/. Feel free to contribute at any time :)

**Comment by ryshoooo** [comment]
Hi. Due to the lack of activity from the maintainers, we've decided to fork this repository (https://github.com/adamatics/adamatics-keycloak) and take the maintenance burden, in order to keep the python keycloak client fresh and updated. We aim to release very frequently, but we also aim to increase the test coverage dramatically. We've included your changes in our forked release, see https://pypi.org/project/adamatics-keycloak/. Feel free to contribute at any time :)

**Comment by harmannkibue** [comment]
Hi, am glad that we can keep the project active.I am happy to continue contributing.Thank you

**Comment by ryshoooo** [comment]
This is a duplicate of #267 which has been merged. Thank you for your contribution! I'll be closing this PR as it's a duplicate :)

**Pull request closed without merging**
